name: Update Language Stats
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history

      - name: Install LinguistJS
        run: npm install -g linguist-js

      - name: Generate Stats
        run: |
          linguist --analyze ./ --json > stats.json
          echo "LANGUAGE_TABLE=$(jq -r '.languages.results | to_entries[] | "| \(.key) | \(.value.count) | \(.value.bytes/1024 | round)KB |"' stats.json)" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i '/<!-- LANGUAGES_START -->/,/<!-- LANGUAGES_END -->/c\
          <!-- LANGUAGES_START -->\
          | Language | Files | Size |\
          | -------- | ----- | ---- |\
          ${{ env.LANGUAGE_TABLE }}\
          <!-- LANGUAGES_END -->' README.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: Update language stats'
          file_pattern: README.md
          push_options: '--force'  # Force push to handle history divergence
          skip_fetch: true  # Prevent redundant fetch
