name: Update Language Stats
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get language statistics from GitHub API
        run: |
          REPO="${GITHUB_REPOSITORY}"
          curl -s "https://api.github.com/repos/${REPO}/languages" > languages.json
          
          # Create formatted table
          echo "LANGUAGE_TABLE<<EOF" >> $GITHUB_ENV
          echo "| Language | Size |" >> $GITHUB_ENV
          echo "| -------- | ---- |" >> $GITHUB_ENV
          jq -r 'to_entries | sort_by(-.value) | .[] | "| \(.key) | \(.value/1024 | round)KB |"' languages.json >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update README
        run: |
          # Verify markers exist
          if grep -q "<!-- LANGUAGES_START -->" README.md && grep -q "<!-- LANGUAGES_END -->" README.md; then
            sed -i '/<!-- LANGUAGES_START -->/,/<!-- LANGUAGES_END -->/c\<!-- LANGUAGES_START -->\n'"$LANGUAGE_TABLE"'\n<!-- LANGUAGES_END -->' README.md
            echo "README.md updated successfully"
          else
            echo "Warning: Markers not found in README.md"
            echo "LANGUAGE_TABLE:"
            echo "$LANGUAGE_TABLE"
          fi

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: Update language stats'
          file_pattern: README.md
          push_options: '--force'
