name: Update Language Stats
on:
  push:
    branches: [ main ]  
  workflow_dispatch:    

jobs:
  linguist-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install LinguistJS
      run: npm install linguist-js

    - name: Generate Language Stats
      run: |
        npx linguist-js --json --listFiles > stats.json
        echo "LANGUAGE_STATS=$(jq -c '.languages.results' < stats.json)" >> $GITHUB_ENV

    - name: Update README
      run: |
        sed -i "/<!-- LANGUAGES_START -->/,/<!-- LANGUAGES_END -->/c\\
        <!-- LANGUAGES_START -->\\
        $(node -e "const data = JSON.parse(process.env.LANGUAGE_STATS); \
        console.log(Object.entries(data) \
          .map(([lang, stats]) => \`| \${lang} | \${stats.count} | \${(stats.bytes/1024).toFixed(1)}KB |\`) \
          .join('\\n'));") \\
        <!-- LANGUAGES_END -->" README.md

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'docs: Update language statistics'
