name: Update Language Stats
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get language statistics from GitHub API
        run: |
          REPO="${GITHUB_REPOSITORY}"
          curl -s "https://api.github.com/repos/${REPO}/languages" > languages.json
          
          # Create temporary file with table contents
          echo "| Language | Size |" > table.md
          echo "| -------- | ---- |" >> table.md
          jq -r 'to_entries | sort_by(-.value) | .[] | "| \(.key) | \(.value/1024 | floor)KB |"' languages.json >> table.md
          
          if [ ! -s table.md ]; then
            echo "| No languages detected | - |" >> table.md
          fi

      - name: Update README
        run: |
          # Create new README with updated content
          awk '
          BEGIN {printedMarker=0; foundStart=0;}
          /<!-- LANGUAGES_START -->/ {
            print $0;
            system("cat table.md");
            foundStart=1;
            printedMarker=1;
            next;
          }
          /<!-- LANGUAGES_END -->/ {
            if (foundStart) {
              print $0;
              printedMarker=0;
              foundStart=0;
            } else {
              print $0;
            }
            next;
          }
          foundStart==0 {print $0}
          ' README.md > README.new
          
          mv README.new README.md
          
          echo "Updated README content:"
          cat README.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: Update language stats'
          file_pattern: README.md
          push_options: '--force'

