name: Update All GitHub Stats
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install axios
        
      - name: Run GitHub stats dashboard script
        env:
          GITHUB_USERNAME: ${{ github.repository_owner }}
          # Using a personal access token for higher rate limits and access to all repos
          # Create this token in your GitHub settings and add as a repository secret
          GITHUB_TOKEN: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
        run: node scripts/dashboard.js
        
      - name: Debug output
        run: |
          echo "Stats file content:"
          cat stats.json || echo "stats.json not found"
          echo "README content:"
          cat README.md || echo "README.md not found"
        
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: Update GitHub stats across all repositories'
          file_pattern: 'README.md stats.json'
          push_options: '--force'
