name: Update Language Stats
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linguist-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install LinguistJS
      run: npm install linguist-js

    - name: Generate Language Stats
      run: |
        npx linguist-js --analyze ./ --json > stats.json
        LANGUAGE_TABLE=$(node -e "
          try {
            const data = require('./stats.json').languages.results;
            let table = '| Language | Files | Size |\\n| -------- | ----- | ---- |\\n';
            Object.entries(data)
              .sort(([,a], [,b]) => b.count - a.count)
              .forEach(([lang, stats]) => {
                table += `| ${lang} | ${stats.count} | ${(stats.bytes/1024).toFixed(1)}KB |\\n`;
              });
            console.log(table);
          } catch (e) {
            console.error('Error generating table:', e);
            process.exit(1);
          }
        ")
        echo "LANGUAGE_TABLE<<EOF" >> $GITHUB_ENV
        echo "$LANGUAGE_TABLE" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Update README
      run: |
        perl -i -0pe 's/<!-- LANGUAGES_START -->.*?<!-- LANGUAGES_END -->/<!-- LANGUAGES_START -->\n$ENV{LANGUAGE_TABLE}\n<!-- LANGUAGES_END -->/s' README.md
        
        echo "Updated README content:"
        cat README.md

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'docs: Update language statistics'
        file_pattern: 'README.md'

